//> using scala 2.13.15
//> using resourceDir ./src/main/resources
//> using test.resourceDir ./test/main/resources
//> using dep org.axle-lang::axle-core:0.6.6
//> using dep org.axle-lang::axle-xml:0.6.6
//> using dep org.axle-lang::axle-jblas:0.6.6
//> using dep org.axle-lang::axle-joda:0.6.6
//> using dep net.sf.jung:jung-visualization:2.1.1
//> using dep net.sf.jung:jung-algorithms:2.1.1
//> using dep net.sf.jung:jung-api:2.1.1
//> using dep net.sf.jung:jung-graph-impl:2.1.1
//> using dep io.monix::monix-reactive:3.4.1
//> using dep joda-time:joda-time:2.13.0
//> using dep org.joda:joda-convert:2.2.3
//> using dep org.jblas:jblas:1.2.5
//> using dep org.scala-lang.modules::scala-xml:2.3.0
//> using dep org.scalatest::scalatest:3.2.19
//> using test.dep org.scalameta::munit:1.0.2
